-- ================================================================
-- Sistema: MediAlert Cloud Native
-- Componente: Oracle XE en Docker
-- Usuario esperado: ALERTAS_APP
-- Password esperado: Alertas123
-- Servicio esperado: XEPDB1
--
-- IMPORTANTE:
-- En docker-compose.vm.yml se crea automaticamente el usuario ALERTAS_APP
-- con las variables APP_USER y APP_USER_PASSWORD del contenedor gvenzl/oracle-xe.
-- Este script crea las tablas del sistema dentro de ese esquema.
-- ================================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SESSION SET CURRENT_SCHEMA = ALERTAS_APP;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ALERTA_VITAL CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ALERTA_VITAL_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

CREATE SEQUENCE ALERTA_VITAL_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE ALERTA_VITAL (
  ID NUMBER PRIMARY KEY,
  PACIENTE_RUT VARCHAR2(20) NOT NULL,
  PACIENTE_NOMBRE VARCHAR2(120) NOT NULL,
  TIPO_SIGNO VARCHAR2(60) NOT NULL,
  VALOR NUMBER(12,2) NOT NULL,
  UNIDAD VARCHAR2(20) NOT NULL,
  UMBRAL_MINIMO NUMBER(12,2) NOT NULL,
  UMBRAL_MAXIMO NUMBER(12,2) NOT NULL,
  GRAVEDAD VARCHAR2(20) NOT NULL,
  ESTADO VARCHAR2(20) DEFAULT 'NUEVA' NOT NULL,
  MENSAJE VARCHAR2(250) NOT NULL,
  OBSERVACION VARCHAR2(500),
  FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CHK_ALERTA_ESTADO CHECK (ESTADO IN ('NUEVA', 'ATENDIDA', 'DESCARTADA')),
  CONSTRAINT CHK_ALERTA_GRAVEDAD CHECK (GRAVEDAD IN ('MEDIA', 'ALTA', 'CRITICA')),
  CONSTRAINT CHK_ALERTA_UMBRAL CHECK (UMBRAL_MINIMO < UMBRAL_MAXIMO)
);

CREATE INDEX IDX_ALERTA_ESTADO ON ALERTA_VITAL (ESTADO);
CREATE INDEX IDX_ALERTA_RUT ON ALERTA_VITAL (PACIENTE_RUT);
CREATE INDEX IDX_ALERTA_FECHA ON ALERTA_VITAL (FECHA_REGISTRO);

INSERT INTO ALERTA_VITAL (
  ID, PACIENTE_RUT, PACIENTE_NOMBRE, TIPO_SIGNO, VALOR, UNIDAD,
  UMBRAL_MINIMO, UMBRAL_MAXIMO, GRAVEDAD, ESTADO, MENSAJE, OBSERVACION
) VALUES (
  ALERTA_VITAL_SEQ.NEXTVAL, '12.345.678-9', 'Paciente Demo Uno', 'FRECUENCIA_CARDIACA', 132, 'lpm',
  60, 100, 'CRITICA', 'NUEVA', 'Valor sobre el umbral maximo para FRECUENCIA_CARDIACA', 'Dato inicial para prueba Postman'
);

INSERT INTO ALERTA_VITAL (
  ID, PACIENTE_RUT, PACIENTE_NOMBRE, TIPO_SIGNO, VALOR, UNIDAD,
  UMBRAL_MINIMO, UMBRAL_MAXIMO, GRAVEDAD, ESTADO, MENSAJE, OBSERVACION
) VALUES (
  ALERTA_VITAL_SEQ.NEXTVAL, '18.765.432-1', 'Paciente Demo Dos', 'SATURACION_OXIGENO', 88, '%',
  92, 100, 'ALTA', 'NUEVA', 'Valor bajo el umbral minimo para SATURACION_OXIGENO', 'Dato inicial para prueba frontend'
);

INSERT INTO ALERTA_VITAL (
  ID, PACIENTE_RUT, PACIENTE_NOMBRE, TIPO_SIGNO, VALOR, UNIDAD,
  UMBRAL_MINIMO, UMBRAL_MAXIMO, GRAVEDAD, ESTADO, MENSAJE, OBSERVACION
) VALUES (
  ALERTA_VITAL_SEQ.NEXTVAL, '20.111.222-3', 'Paciente Demo Tres', 'TEMPERATURA', 39.2, 'C',
  36, 37.5, 'ALTA', 'ATENDIDA', 'Valor sobre el umbral maximo para TEMPERATURA', 'Registro atendido para validar filtros'
);

COMMIT;

SELECT ID, PACIENTE_RUT, PACIENTE_NOMBRE, TIPO_SIGNO, VALOR, ESTADO
FROM ALERTAS_APP.ALERTA_VITAL
ORDER BY ID;
