ALTER SESSION SET CURRENT_SCHEMA=MEDIALERT;
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE ALERTA_VITAL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE RESUMEN_VITAL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN
 EXECUTE IMMEDIATE 'CREATE TABLE ALERTA_VITAL (
  ID NUMBER(19) PRIMARY KEY, MENSAJE_ID VARCHAR2(80) UNIQUE, PACIENTE_ID NUMBER(19),
  PACIENTE_RUT VARCHAR2(20) NOT NULL, PACIENTE_NOMBRE VARCHAR2(120) NOT NULL,
  TIPO_SIGNO VARCHAR2(60) NOT NULL, VALOR NUMBER(18,4), UNIDAD VARCHAR2(20),
  UMBRAL_MINIMO NUMBER(18,4), UMBRAL_MAXIMO NUMBER(18,4), TIPO_ANOMALIA VARCHAR2(80) NOT NULL,
  DETALLE VARCHAR2(500) NOT NULL, SEVERIDAD VARCHAR2(20) NOT NULL, FECHA_HORA TIMESTAMP WITH TIME ZONE NOT NULL,
  ESTADO VARCHAR2(20) DEFAULT ''NUEVA'' NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN
 EXECUTE IMMEDIATE 'CREATE TABLE RESUMEN_VITAL (
  ID NUMBER(19) PRIMARY KEY, MENSAJE_ID VARCHAR2(80) UNIQUE NOT NULL, PACIENTE_RUT VARCHAR2(20) NOT NULL,
  PACIENTE_NOMBRE VARCHAR2(120) NOT NULL, PERIODO_MINUTOS NUMBER(10), CANTIDAD_MEDICIONES NUMBER(10),
  PROMEDIO_FRECUENCIA_CARDIACA NUMBER(18,4), PROMEDIO_SATURACION_OXIGENO NUMBER(18,4),
  CLASIFICACION VARCHAR2(20) NOT NULL, OBSERVACION VARCHAR2(500), FECHA_HORA TIMESTAMP WITH TIME ZONE NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN
 EXECUTE IMMEDIATE 'CREATE TABLE EVENTO_PROCESADO (MENSAJE_ID VARCHAR2(80) PRIMARY KEY, TIPO VARCHAR2(30) NOT NULL, PROCESADO_EN TIMESTAMP WITH TIME ZONE NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
COMMIT;
